sudo: false
branches:
  only:
    - master
language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  # - python setup.py install
  - coverage run -m pytest tests -v
after_success:
  - codecov
notifications:
    email:
        on_success: change
        on_failure: always